/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as BkkRouteImport } from './routes/bkk'
import { Route as BludRouteImport } from './routes/blud'
import { Route as ChatAiRouteImport } from './routes/chat-ai'
import { Route as PpdbRouteImport } from './routes/ppdb'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const BkkRoute = BkkRouteImport.update({
  id: '/bkk',
  path: '/bkk',
  getParentRoute: () => rootRouteImport,
} as any)
const BludRoute = BludRouteImport.update({
  id: '/blud',
  path: '/blud',
  getParentRoute: () => rootRouteImport,
} as any)
const ChatAiRoute = ChatAiRouteImport.update({
  id: '/chat-ai',
  path: '/chat-ai',
  getParentRoute: () => rootRouteImport,
} as any)
const PpdbRoute = PpdbRouteImport.update({
  id: '/ppdb',
  path: '/ppdb',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/bkk': typeof BkkRoute
  '/blud': typeof BludRoute
  '/chat-ai': typeof ChatAiRoute
  '/ppdb': typeof PpdbRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/bkk': typeof BkkRoute
  '/blud': typeof BludRoute
  '/chat-ai': typeof ChatAiRoute
  '/ppdb': typeof PpdbRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/bkk': typeof BkkRoute
  '/blud': typeof BludRoute
  '/chat-ai': typeof ChatAiRoute
  '/ppdb': typeof PpdbRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/bkk' | '/blud' | '/chat-ai' | '/ppdb'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/bkk' | '/blud' | '/chat-ai' | '/ppdb'
  id: '__root__' | '/' | '/bkk' | '/blud' | '/chat-ai' | '/ppdb'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  BkkRoute: typeof BkkRoute
  BludRoute: typeof BludRoute
  ChatAiRoute: typeof ChatAiRoute
  PpdbRoute: typeof PpdbRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/bkk': {
      id: '/bkk'
      path: '/bkk'
      fullPath: '/bkk'
      preLoaderRoute: typeof BkkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blud': {
      id: '/blud'
      path: '/blud'
      fullPath: '/blud'
      preLoaderRoute: typeof BludRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/chat-ai': {
      id: '/chat-ai'
      path: '/chat-ai'
      fullPath: '/chat-ai'
      preLoaderRoute: typeof ChatAiRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ppdb': {
      id: '/ppdb'
      path: '/ppdb'
      fullPath: '/ppdb'
      preLoaderRoute: typeof PpdbRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  BkkRoute: BkkRoute,
  BludRoute: BludRoute,
  ChatAiRoute: ChatAiRoute,
  PpdbRoute: PpdbRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
