name: Deploy Web Sekolah

on:
  push:
    branches:
      - main

permissions:
  contents: read

jobs:
  deploy:
    runs-on: [self-hosted, linux, x64]

    steps:
      - name: Checkout source
        uses: actions/checkout@v4

      - name: Build Docker image
        run: docker build --network=host -t web-sekolah:${{ github.sha }} .

      - name: Remove old container
        run: docker rm -f web-sekolah || true

      - name: Start new container
        run: |
          docker network inspect web-sekolah-net >/dev/null 2>&1 || docker network create web-sekolah-net

          docker run -d \
            --name web-sekolah \
            --restart unless-stopped \
            --network web-sekolah-net \
            --env-file /home/andika/secrets/web-sekolah.env \
            -v ppdb_uploads:/app/uploads \
            -p 127.0.0.1:3000:3000 \
            web-sekolah:${{ github.sha }}
            
      - name: Verify container
        run: docker ps --filter "name=web-sekolah"

      - name: Test website internally
        run: |
          sleep 3
          curl --fail http://127.0.0.1:3000

      - name: Clean old Docker data
        run: |
          docker image prune -af
          docker builder prune -af
          docker container prune -f